version: '3'

services:
  metrics-api:
    build: .
    container_name: minecraft-metrics-api
    restart: always
    ports:
      - "${METRICS_API_PORT:-8000}:8000"
    environment:
      - METRICS_API_KEY=${METRICS_API_KEY}
      - METRICS_API_PORT=${METRICS_API_PORT:-8000}
    volumes:
      - /data:/data
      # Mount Docker socket for container metrics
      - /var/run/docker.sock:/var/run/docker.sock
      # Try to mount Minecraft world data if available in different locations
      - /var/lib/docker/volumes/minecraft-server_data/_data:/minecraft_data:ro
    networks:
      - metrics-network
    user: "${UID:-1000}:${GID:-1000}"

networks:
  metrics-network:
    driver: bridge 