version: '3'

services:
  metrics-api:
    build: .
    container_name: minecraft-metrics-api
    restart: always
    ports:
      - "${METRICS_API_PORT:-8000}:8000"
    environment:
      - METRICS_API_KEY=${METRICS_API_KEY}
      - METRICS_API_PORT=${METRICS_API_PORT:-8000}
    volumes:
      - /data:/data
      # Uncomment if you need to access Docker socket
      # - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - metrics-network

networks:
  metrics-network:
    driver: bridge 