version: '3'

services:
  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    restart: on-failure
    command: prefect server start --host 0.0.0.0
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://0.0.0.0:4200/api/health')"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "4200:4200"
    volumes:
      - prefect-data:/root/.prefect
      - ./flows:/opt/prefect/flows
      - ${HOME}/.aws:/root/.aws:ro
    environment:
      # Internal URLs for server use - inside container
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_UI_URL=http://0.0.0.0:4200
      # External URLs for client use - accessible from outside
      - PREFECT_UI_API_URL=http://${PREFECT_HOST:-localhost}:4200/api
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
      - PREFECT_LOGGING_LEVEL=DEBUG
      - PREFECT_HOME=/root/.prefect
      # Use aiosqlite for async support
      - PREFECT_SERVER_DATABASE_CONNECTION_URL=sqlite+aiosqlite:////root/.prefect/prefect.db
    networks:
      prefect-network:
        # Assign a static IP to the server
        ipv4_address: 172.28.0.2

  prefect-worker:
    image: prefecthq/prefect:3-latest
    container_name: prefect-worker
    restart: on-failure
    # Simpler command to start the worker
    entrypoint: /bin/bash
    command: -c "prefect work-pool create default -t process || echo 'Work pool already exists' && prefect worker start --pool default"
    volumes:
      - prefect-data:/root/.prefect
      - ./flows:/opt/prefect/flows
      - ${HOME}/.aws:/root/.aws:ro
      - ${HOME}/.ssh:/root/.ssh:ro
    environment:
      # Use the IP address instead of hostname - needs to be accessible from worker
      - PREFECT_API_URL=http://172.28.0.2:4200/api
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
      # Add extra logging to help debug
      - PREFECT_LOGGING_LEVEL=DEBUG
      - PREFECT_HOME=/root/.prefect
      # Make sure server is healthy before starting
      - PREFECT_CLIENT_MAX_RETRIES=10
    networks:
      prefect-network:
        # Assign a static IP to the worker
        ipv4_address: 172.28.0.3
    # Add extra hosts mapping to resolve hostname issues
    extra_hosts:
      - "prefect-server:172.28.0.2"
    depends_on:
      prefect-server:
        condition: service_healthy

volumes:
  prefect-data:
    driver: local

networks:
  prefect-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16